### ISSUE TITLE
Equivalence checker is not symmetric

### ISSUE THREAD

**Issue by FlorianCassayre** [epfl-lara/lisa#12]
Consider the following snippet:
```Scala
import lisa.kernel.fol.FOL.*
import lisa.KernelHelpers.*

val a = PredicateFormula(SchematicPredicateLabel("a", 0), Seq.empty)
val b = PredicateFormula(SchematicPredicateLabel("b", 0), Seq.empty)
val f1 = a ==> (a \/ b)
val f2 = b ==> b
assert(isSame(f1, f2) == isSame(f2, f1))
```
The assertion fails to verify because `isSame(f1, f2) == false` while `isSame(f2, f1) == true`.

I think this is unintended behavior. Moreover we should clearly specify in the documentation which properties hold and which do not (e.g. symmetry, transitivity, preservation after substitution).

**Comment by SimonGuilloud** [comment]
Well, good catch, that's a surprising one. It should be true in both case.
For the doc, I believe what it does eexactly is explained in the user manual.

**Comment by SimonGuilloud** [comment]
Got it. Was complicated to track down, but I found the culprit. 

For detailed explanation: It was the checkForContradiction function, which given a list of formulas in normal form check if some element is the negation of another element of the list.  The list at that point is split into positive and (body of) negative formulas, before checking for collision (by code) between the two.
Then the collision check is made efficiently because the two lists are sorted by their code.
While the negative one was being sorted anyway after the split, the positive list was supposed to be already sorted. Except that for efficiency, elements were put in the positive list using Cons ( :: ), effectively reversing the list and preventing the collision check to run fully.

**Comment by FlorianCassayre** [comment]
@SimonGuilloud note that you closed the ticket manually but haven't addressed the issue.
